install.packages("gapminder")
library(gapminder)
str(gapminder)
install.packages("tidyverse")
library(tidyverse)
class(gapminder)
gapminder
head(gapminder)
tail(gapminder)
as_tibble(iris)
names(gapminder)
ncol(gapminder)
length(gapminder)
dim(gapminder)
nrow(gapminder)
summary(gapminder)
plot(lifeExp ~ year, gapminder)
plot(lifeExp ~ gdpPercap, gapminder)
plot(lifeExp ~ log(gdpPercap), gapminder)
head(gapminder$lifeExp)
summary(gapminder$lifeExp)
hist(gapminder$lifeExp)
summary(gapminder$year)
table(gapminder$year)
class(gapminder$continent)
summary(gapminder$continent)
levels(gapminder$continent)
nlevels(gapminder$continent)
table(gapminder$continent)
barplot(table(gapminder$continent))
